// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZT23_XXDUV16FUFBvt7hkbS08jfzrVoc',
    appId: '1:901856795489:android:7e1afa6474f5075d6a0320',
    messagingSenderId: '901856795489',
    projectId: 'hotel-tv-app-fbf2b',
    databaseURL: 'https://hotel-tv-app-fbf2b-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-tv-app-fbf2b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsaMmtsuCojaqVuXHCMoZXQdmMgiUREYQ',
    appId: '1:901856795489:ios:72a97e49dffb94fc6a0320',
    messagingSenderId: '901856795489',
    projectId: 'hotel-tv-app-fbf2b',
    databaseURL: 'https://hotel-tv-app-fbf2b-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-tv-app-fbf2b.firebasestorage.app',
    iosClientId: '901856795489-fqimic2v2bmdg4kjik87qhrhent5ohvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotel',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmyzlS9C_ErothA4Yqp71LAvWJQbhjZsQ',
    appId: '1:901856795489:web:b608932c0c108c976a0320',
    messagingSenderId: '901856795489',
    projectId: 'hotel-tv-app-fbf2b',
    authDomain: 'hotel-tv-app-fbf2b.firebaseapp.com',
    databaseURL: 'https://hotel-tv-app-fbf2b-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-tv-app-fbf2b.firebasestorage.app',
    measurementId: 'G-1MHE6TPT82',
  );
}
